name: "Tests"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  pytest:
    name: "Unit Tests (Python ${{ matrix.python-version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7.0.1"

      - name: "Set up Python"
        uses: "actions/setup-python@v7.0.0"
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: "Install requirements"
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-test.txt

      - name: "Run tests"
        run: python3 -m pytest tests/ -v --timeout=60
